name: drones
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - albucore=0.0.24
  - albumentations=2.0.8
  - annotated-types=0.6.0
  - anywidget=0.9.18
  - aom=3.6.0
  - arrow-cpp=21.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=2.137
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - eigen=5.0.1
  - eval-type-backport=0.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.16
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.42
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icu=73.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jpeg=9e
  - jupyter-ui-poll=1.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.2
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcups=2.4.15
  - libcurl=8.15.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.6
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openblas=0.3.30
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.12
  - openssl=3.5.4
  - orc=2.2.0
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - psygnal=0.14.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.0.1
  - qtbase=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - rerun-sdk=0.24.1
  - s2n=1.5.25
  - scipy=1.15.3
  - setuptools=78.1.1
  - simsimd=6.5.0
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - stringzilla=4.6.0
  - tesseract=5.2.0
  - tk=8.6.14
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-inspection=0.4.2
  - typing_extensions=4.14.1
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - acconeer-exptool==7.17.6
      - addict==2.4.0
      - aiosignal==1.3.2
      - annotated-doc==0.0.4
      - anyio==4.12.1
      - apriltag==0.0.16
      - argcomplete==3.6.3
      - attrdict3==2.0.2
      - attributes-doc==0.4.0
      - attrs==25.3.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - bs4==0.0.2
      - catkin-pkg==1.0.0
      - cbor2==5.8.0
      - certifi==2025.4.26
      - cffi==2.0.0
      - charset-normalizer==3.4.2
      - clarabel==0.11.1
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.2
      - commonmark==0.9.1
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cssutils==2.11.1
      - cvxpy==1.7.3
      - cycler==0.10.0
      - darkdetect==0.7.1
      - dash==3.0.4
      - distro==1.9.0
      - dm-tree==0.1.9
      - docutils==0.21.2
      - empy==3.3.4
      - evo==1.34.0
      - exceptiongroup==1.1.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.0.3
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - g2o-python==0.0.12
      - grpcio==1.73.0
      - gym==0.23.0
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.10
      - imageio==2.37.0
      - itsdangerous==2.2.0
      - jax-jumpy==1.0.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kitti2bag==1.5
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - libusb-package==1.0.26.3
      - lietorch==0.3
      - ll-xist==5.83
      - lz4==4.4.4
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - msgpack==1.1.1
      - narwhals==1.42.1
      - natsort==8.4.0
      - nbformat==5.10.4
      - numexpr==2.14.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - osqp==1.0.5
      - pandas==2.3.0
      - pillow==9.5.0
      - plotly==6.1.2
      - progressbar2==4.5.0
      - protobuf==6.31.1
      - pupil-apriltags==1.0.4.post11
      - pyarrow==20.0.0
      - pybullet==3.2.7
      - pycoco==0.7.2
      - pycocotools==2.0.11
      - pycparser==2.23
      - pygame==2.6.1
      - pygments==2.19.1
      - pykitti==0.3.1
      - pyparsing==3.2.3
      - pyperclip==1.11.0
      - pyqtdarktheme==2.1.0
      - pyqtgraph==0.14.0
      - pyquaternion==0.9.9
      - pyside6==6.8.3
      - pyside6-addons==6.8.3
      - pyside6-essentials==6.8.3
      - python-utils==3.9.1
      - pytz==2025.2
      - pyusb==1.3.1
      - pyyaml==6.0.2
      - qtawesome==1.4.1
      - qtpy==2.4.3
      - ray==2.37.0
      - referencing==0.36.2
      - regex==2026.1.15
      - requests==2.32.4
      - rerun-notebook==0.24.1
      - retrying==1.3.4
      - rich==12.6.0
      - rosbags==0.11.0
      - rpds-py==0.25.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-build==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.7.0
      - scs==3.2.9
      - seaborn==0.13.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - shiboken6==6.8.3
      - soupsieve==2.8.3
      - stable-baselines3==2.0.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - textual==0.1.18
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tokenizers==0.22.2
      - tomli==2.2.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - transformers==5.1.0
      - trimesh==4.6.12
      - triton==3.2.0
      - typer==0.23.1
      - typer-slim==0.23.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - xlsxwriter==3.2.9
      - zstandard==0.25.0