name: drones
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.22
      - pillow>=9.0
      - matplotlib>=3.5
      - cycler>=0.10
      - gym==0.23.0
      - pybullet>=3.2
      - torch==2.5.1
      - ray[rllib]==2.37.0
      - stable-baselines3==2.0.0
      - scipy>=1.8
      - tensorboard>=2.9